global:
  scrape_interval: 60s
  evaluation_interval: 60s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Nutanix Exporter
  - job_name: 'nutanix-exporter'
    static_configs:
      - targets: ['nutanix-exporter:8080']
    scrape_interval: 60s
    scrape_timeout: 30s
    #metrics_path: /metrics  - Note uncomment and comment out metrics_path: /health if no results or connection reset issues
    metrics_path: /health
    honor_labels: true
    
    # Optional: Add labels to identify this exporter instance
    relabel_configs:
      - target_label: __address__
        replacement: nutanix-exporter:8080
    
    # Optional: Add custom labels
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nutanix_.*'
        target_label: exporter
        replacement: 'nutanix'

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
